name: Move Issue to Another Project
on:
  issues:
    types: [milestoned]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move Issue
        run: |
          issue_number="ISSUE_NUMBER"
          from_project_id="1"
          to_project_id="2"
          milestone_title="operations"
          token="${{ secrets.SEHA-TOKEN }}"
          
          # Get the current issue data
          issue=$(curl -s -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue_number")
          issue_id=$(echo $issue | jq -r '.id')
          milestone=$(echo $issue | jq -r '.milestone.title')

          if [ "$milestone" == "$milestone_title" ]; then
            # Move the issue to the target project
            curl -X POST -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.inertia-preview+json" \
              -H "Content-Type: application/json" -d "{\"content_type\": \"Issue\", \"content_id\": $issue_id}" \
              "https://api.github.com/projects/columns/$to_project_id/cards"
            
            # Remove the issue from the current project
            card_id=$(echo $issue | jq -r '.project_card.id')
            if [ "$card_id" != "null" ]; then
              curl -X DELETE -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.inertia-preview+json" \
                "https://api.github.com/projects/columns/cards/$card_id"
            fi
          else
            echo "Issue does not have the target milestone. Skipping move to another project."
          fi
